apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  labels:
    label-one: "value-one"
  name: containernodepool-sample
spec:
  location: us-central1-c
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 3
  nodeConfig:
    machineType: n1-standard-1
    diskSizeGb: 100
    diskType: pd-standard
    tags:
      - tagone
      - tagtwo
    preemptible: false
    # minCpuPlatform: "Intel Haswell"
    oauthScopes:
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
    # guestAccelerator:
    #   - type: "nvidia-tesla-k80"
    #     count: 1
    metadata:
      disable-legacy-endpoints: "true"
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: iowa
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "false"
  labels:
    label-one: "value-one"
  name: iowa
spec:
  location: us-central1-c
  initialNodeCount: 2