apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  # annotations:
  #   cnrm.cloud.google.com/deletion-policy: abandon
  labels:
    env: prod
    director: lean
    producer: tarantino
  name: kcc-topic