apiVersion: redis.cnrm.cloud.google.com/v1beta1
kind: RedisInstance
metadata:
  name: redisinstance-sample
  namespace: kcc
spec:
  displayName: Sample KCC-created Redis Instance
  region: europe-west2
  tier: BASIC
  memorySizeGb: 1